Create pipeline from existing code
j-adamczyk/Document_OCR_scanner pull request #11
Opened 2021-02-24 21:08 UTC by konrrad

2021-03-01 09:58 UTC, j-adamczyk requested changes

2021-03-01 09:58 UTC, j-adamczyk commented on main.py
> +parser.add_argument("image_filename")
It's nice to create function like `get_parsed_args()` which creates parser, parses arguments and returns the argparse.Namespace object

2021-03-01 09:58 UTC, j-adamczyk commented on main.py
> +    utils.show_image(image, "transformed")
Separate main function is not required, it's better to do this in `if __name__ == __main__`

2021-03-01 09:58 UTC, j-adamczyk commented on sheet_cutting.py
>      import imutils
This import should not be local, just do global import, or, even better, just copy this function from imutils (it's a thin wrapper library around more standard libraries).

2021-03-01 09:58 UTC, j-adamczyk commented on sheet_cutting.py
> +            points arranged anti-clockwise
Double indent unnecessary, should be:
```
-------
list
    points arranged anti-clockwise
```

2021-03-01 09:58 UTC, j-adamczyk commented on sheet_cutting.py
> +        # ((center_x,center_y),(width,height),angle)
Add spaces after commas

2021-03-01 09:58 UTC, j-adamczyk commented on utils.py
> +    return [(0, 0), (0, image.shape[0] - 1), (image.shape[1] - 1, image.shape[0] - 1), (image.shape[1] - 1, 0)]
Line >80 characters, please break into 4 lines

2021-03-01 09:58 UTC, j-adamczyk commented on utils.py
> +def show_image(image: np.ndarray, window_title="image"):
Multiple arguments should be in separate lines, `window_title` lacks type

2021-03-01 09:58 UTC, j-adamczyk commented on utils.py
> +    window_title
Add `window_type` docstring

2021-03-01 09:58 UTC, j-adamczyk commented on sheet_cutting.py
> +    points[3] = tmp
This just swaps `points[1]` and `points[3]`, just use regular Python swap:
```
points[1], points[3] = points[3], points[1]
```

2021-03-01 09:58 UTC, j-adamczyk commented on sheet_cutting.py
> +    points
Lacks type

2021-03-01 09:58 UTC, j-adamczyk commented on main.py
> +import utils
Imports from the project itself should be at the end, so:
```
# Python build-in modules

# 3rd party libraries

# project modules
```

2021-03-01 09:58 UTC, j-adamczyk commented on main.py
> +    image = align_text(image.copy())
Why image copies?

2021-03-01 09:58 UTC, j-adamczyk commented on sheet_cutting.py
>      def get_rect_size(rect: np.ndarray):
Lacks docstring

2021-03-31 11:53 UTC, j-adamczyk commented on main.py
> +#project modules
Comments should start with a space

2021-03-31 11:53 UTC, j-adamczyk commented on main.py
> +def get_parsed_args():
Lacks returned type and docstring

2021-03-31 11:53 UTC, j-adamczyk commented on main.py
> +    parser.add_argument("image_filename")
Should have description

2021-03-31 11:53 UTC, j-adamczyk commented on sheet_cutting.py
> +def grab_contours(cnts):
Add `cnts` data type and returned type

2021-04-01 17:17 UTC, j-adamczyk approved these changes

2021-04-01 17:25 UTC, wojtke approved these changes

2021-04-01 17:26 UTC, merged