Image rescaling
j-adamczyk/Document_OCR_scanner pull request #12
Opened 2021-03-01 21:21 UTC by wolski0420

2021-03-01 21:35 UTC, j-adamczyk requested changes

2021-03-01 21:35 UTC, j-adamczyk commented on rescaling.py
> +import os
Order of imports should be:
```
# Python built-in modules

# 3rd party libraries

# project libraries
```

2021-03-01 21:35 UTC, j-adamczyk commented on rescaling.py
> +    os.remove(filename)
You can use `StringIO` or `BytesIO` buffers from the `io` built-in module. They act as temporary files in RAM, allowing programmer to use objects that require file interface entirely in RAM. It's faster than disk operations.

2021-03-01 21:35 UTC, j-adamczyk commented on rescaling.py
> +    scikit.imsave(f"{filename.split('.')[0]}_rescaled.jpg", img_as_ubyte(rescaled_img))
Remove for PR

2021-03-03 16:03 UTC, wolski0420 commented
I made changes as you suggested. I had to replace matplotlib with PIL because of loading np.ndarray image to matplotlib problem - matplotlib probably requires more complicated structure than a typical array in numpy

2021-03-31 11:56 UTC, j-adamczyk approved these changes

2021-03-31 12:43 UTC, konrrad approved these changes

2021-03-31 14:50 UTC, merged